## Disclaimer: This file is not kept up to date, and just for experimental purposes. Please look into ``generateMatrices.py``

In [1]:
import numpy as np
# from random import *
import matplotlib.pyplot as plt
from skimage import io, viewer

import sys
print("You are running python", sys.version)

/Users/paulw/opt/anaconda3/lib/python3.7/site-packages/skimage/viewer/utils/__init__.py:1: UserWarning: Recommended matplotlib backend is `Agg` for full skimage.viewer functionality.
  from .core import *


You are running python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)]


In [2]:
# The main object: the matrix

class Matrix:
    def __init__(self, size, density, name):
        self.name = name
        self.size = size
        self.array = np.random.rand(size, size)
        self.density = density
        self.isTest = False
        self.array[self.array > (1-density)] = 1 # first this operatio
        self.array[self.array <= (1-density)] = 0

    def print_size(self):
        print( "The size of " , self.name , " is " , self.size)

    def show_image(self):
        viewer.ImageViewer(self.array).show()

In [4]:

mat01 = Matrix(128, .2, 'mat01')
Matrix.print_size(mat01)
# print(mat01.array)
# print(mat01.array.size)
# mat01.array[mat01.array > .4] = 1
# mat01.array[mat01.array <= .4] = 0

print(mat01.array)
print(mat01.array.size)
mat01.show_image()

The size of  mat01  is  128
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 1.]]
16384
